### ISSUE TITLE
Patch on Haikuports

### ISSUE THREAD

**Issue by richienyhus** [Barrett17/Caya#9]
There is a Patch on Haikuports that should be up streamed here.

https://bitbucket.org/haikuports/haikuports/raw/94dae83b75f2dfac47aeae4f53c4ed1452b59a46/haiku-apps/caya/patches/caya-2013.10.12.patchset

**Comment by Barrett17** [comment]
If people continue to report things out of there there's not chance i'll return to work on Caya. It's the second time i see a patch from PulkoMandy in haikuports but not reported here. I'll apply it as soon as i can, thanks for noticing it.

**Comment by Barrett17** [comment]
This patch is now outdated. Caya is now compiling under both gcc2 and gcc4. For any follow up problem open another ticked.
